server:
  port: 9090
#  servlet:
#    context-path: /api

---
spring:
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/ecommerce
    username: postgres
    password: 123
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: 'true'
    hibernate:
      ddl-auto: create-drop
    show-sql: true
  servlet:
    multipart:
      max-request-size: 10MB
      max-file-size: 10MB


server:
  error:
    include-message: always